// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gnkddcdflamrhoaqnvnh.supabase.co";
const ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdua2RkY2RmbGFtcmhvYXFudm5oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE1NzU0NzksImV4cCI6MjA1NzE1MTQ3OX0.tBDSTmxYbQdnt44rFfSMmHvNbHSazxuCj8eCzrPtwM0";
const SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdua2RkY2RmbGFtcmhvYXFudm5oIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0MTU3NTQ3OSwiZXhwIjoyMDU3MTUxNDc5fQ.WDRMFdwtraODIg1bSF4piizzeO25UStqYztk-5TrQwg";

// Regular client for normal operations
export const supabase = createClient<Database>(SUPABASE_URL, ANON_KEY);

// Admin client for privileged operations (delete)
export const adminSupabase = createClient<Database>(SUPABASE_URL, SERVICE_KEY);